default: &default
  adapter: mysql2
  username: root
  password:
  encoding: utf8
  socket: /tmp/mysql.sock
  reconnect: true

development:
  <<: *default
  database: moviepilot_development

production:
  <<: *default
  database: moviepilot_development

test:
  <<: *default
  database: moviepilot_test
